### ISSUE TITLE
Logger.error is not a function

### ISSUE THREAD

**Issue by johnkozan** [ConsenSys/truffle-solidity-loader#1]
Logger.error is undefined. Called here:
`https://github.com/ConsenSys/truffle-solidity-loader/blob/master/index.js#L85`

probably here also: 
`https://github.com/ConsenSys/truffle-solidity-loader/blob/master/index.js#L91`

**Comment by jmdfm** [comment]
Fixed in ee492161777fef667e5ea606bcd0bdcd4681956b
