### ISSUE TITLE
Multiple concurrent runs

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle-solidity-loader#2]
I'm under a time crunch so I can't give too much information at the moment. But the basically, I added about 7 `import Contract from "contracts/SomeContract.sol` statements (all for different contracts), and hit save, which caused the dev server to run compilation and migrations 7 times (or whatever the number is). Output here:

https://gist.github.com/tcoulter/6402a12ad35690fa14c46bc7890237ff

I'm currently developing, hence some garbage output in there. I'll come back around and create a better bug report after devcon.

**Comment by jmdfm** [comment]
Should be fixed by 3fdec61e4c2dbc3d809968125811701c2073e9c9
